version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vite
    versions:
    - 2.0.0
    - 2.0.0-beta.52
    - 2.0.0-beta.56
    - 2.0.0-beta.60
    - 2.0.0-beta.61
    - 2.0.0-beta.62
    - 2.0.0-beta.64
    - 2.0.0-beta.65
    - 2.0.0-beta.66
    - 2.0.0-beta.67
    - 2.0.0-beta.69
    - 2.0.0-beta.70
    - 2.0.1
    - 2.0.2
    - 2.0.3
    - 2.0.4
    - 2.0.5
    - 2.1.0
    - 2.1.1
    - 2.1.2
    - 2.1.3
    - 2.1.4
    - 2.1.5
    - 2.2.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@vue/compiler-sfc"
    versions:
    - 3.0.10
    - 3.0.5
    - 3.0.6
    - 3.0.7
    - 3.0.9
  - dependency-name: vue
    versions:
    - 3.0.10
    - 3.0.5
    - 3.0.6
    - 3.0.7
    - 3.0.9
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
